[build]
  functions = "functions"
  
[functions]
external_node_modules = ["express"]
node_bundler = "esbuild"

[[functions]]
path = "functions/functions.js"


[[redirects]]
  from = "/shoppinglist"
  to = "/"
  status = 404
  force = true