[build]
functions = 'functions'

[[functions]]
path = "functions/functions.js"

[functions]
external_node_modules = ["express"]
node_bundler = "esbuild"

[[redirects]]
  from = "/shoppinglist"
  to = "/"
  status = 404
  force = true