[build]
  functions = "functions"

[functions]
external_node_modules = ["express"]
node_bundler = "esbuild"


[[redirects]]
  from = "/shoppinglist"
  to = "/"
  status = 404
  force = true

  
[[redirects]]
  from = "/profile"
  to = "/"
  status = 404
  force = true